#!/bin/sh
# Regenerate the real-git fixtures used by the sml-git test suite.
#
# Everything is pinned (identities, dates, core.* config) so the object ids
# are byte-for-byte reproducible on any machine with a modern `git`.  Running
# this script overwrites the committed fixtures; the suite then asserts that
# sml-git reproduces exactly these ids and bytes.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

repo="$work/repo"
mkdir -p "$repo"
cd "$repo"

export GIT_AUTHOR_NAME="Fixture Author"
export GIT_AUTHOR_EMAIL="author@example.com"
export GIT_COMMITTER_NAME="Fixture Committer"
export GIT_COMMITTER_EMAIL="committer@example.com"
export GIT_AUTHOR_DATE="1700000000 +0000"
export GIT_COMMITTER_DATE="1700000000 +0000"

git init -q -b main .
git config core.autocrlf false
git config core.fileMode false
git config commit.gpgsign false
git config tag.gpgsign false

# --- a small text blob with a known, hand-verifiable id ----------------------
printf 'hello\n' > hello.txt

# deterministic high-entropy bytes (AES-CTR keystream over zeros, fixed key/iv)
# so the packer's delta heuristic actually fires (compressible text deltas
# worse than it stores, so we need incompressible content).
gen_bytes() { # $1 = byte count -> base64 text on stdout
  head -c "$1" /dev/zero \
    | openssl enc -aes-256-ctr \
        -K 0000000000000000000000000000000000000000000000000000000000000000 \
        -iv 00000000000000000000000000000000 2>/dev/null \
    | base64 | tr -d '\n' | fold -w 64
}

# --- a larger file so the packer produces real deltas between two versions ---
gen_bytes 24000 > big.txt

git add hello.txt big.txt
git commit -q -m "initial commit"

# second commit: tweak one line of big.txt + add a file in a subdir so we get
# a nested tree, and so big.txt v2 deltas against big.txt v1.
# edit a single line in the middle: the rest stays identical so v2 deltas
# strongly against v1 (a copy of the unchanged regions + a tiny insert).
awk 'NR==200{print "EDITED-LINE-200-EDITED-LINE-200-EDITED-LINE-200-EDITED-LINE-200"; next} {print}' big.txt > big.txt.new
mv big.txt.new big.txt
mkdir -p docs
printf 'see README\n' > docs/note.txt
git add big.txt docs/note.txt
git commit -q -m "second commit: edit big.txt and add docs/note.txt"

# annotated tag on the second commit
GIT_TAGGER_NAME="Fixture Tagger" \
git -c user.name="Fixture Tagger" -c user.email="tagger@example.com" \
    tag -a v1.0 -m "release v1.0"

head_commit=$(git rev-parse HEAD)
first_commit=$(git rev-parse HEAD~1)
head_tree=$(git rev-parse 'HEAD^{tree}')
tag_obj=$(git rev-parse v1.0)
hello_blob=$(git rev-parse 'HEAD:hello.txt')
docs_tree=$(git rev-parse 'HEAD:docs')
note_blob=$(git rev-parse 'HEAD:docs/note.txt')

# ---- capture LOOSE objects (before any packing) -----------------------------
rm -rf "$here/loose"
mkdir -p "$here/loose"
# copy the whole loose object store
( cd .git/objects && find . -type f -not -path './pack/*' -not -path './info/*' \
    | while read -r f; do
        mkdir -p "$here/loose/$(dirname "$f")"
        cp "$f" "$here/loose/$f"
      done )

# ---- index + refs -----------------------------------------------------------
cp .git/index "$here/index"
git pack-refs --all
cp .git/packed-refs "$here/packed-refs"
# also keep a loose ref example
mkdir -p "$here/refs"
printf 'ref: refs/heads/main\n' > "$here/refs/HEAD"
# write the resolved main ref explicitly (in case it was packed)
printf '%s\n' "$head_commit" > "$here/refs/main"

# ---- OFS-delta pack (default repack) ----------------------------------------
rm -rf "$here/pack-ofs"
mkdir -p "$here/pack-ofs"
ofsrepo="$work/ofs"
git clone -q --no-local . "$ofsrepo" 2>/dev/null || cp -R . "$ofsrepo"
( cd "$ofsrepo"
  git repack -adq --window=50 --depth=50
  cp .git/objects/pack/*.pack "$here/pack-ofs/"
  cp .git/objects/pack/*.idx  "$here/pack-ofs/" )

# ---- REF-delta pack (pack-objects without --delta-base-offset) --------------
rm -rf "$here/pack-ref"
mkdir -p "$here/pack-ref"
git rev-list --objects --all | awk '{print $1}' \
  | git pack-objects --no-delta-base-offset --window=50 --depth=50 \
        "$here/pack-ref/pack" >/dev/null

# normalise pack-ofs filenames to a stable name
( cd "$here/pack-ofs"
  for p in *.pack; do mv "$p" pack.pack; done
  for x in *.idx;  do mv "$x" pack.idx;  done )
( cd "$here/pack-ref"
  for p in *.pack; do mv "$p" pack.pack; done 2>/dev/null
  for x in *.idx;  do mv "$x" pack.idx;  done 2>/dev/null )

# ---- record the expected ids/metadata as a manifest -------------------------
{
  echo "# sml-git fixtures manifest (generated by generate.sh)"
  echo "head_commit $head_commit"
  echo "first_commit $first_commit"
  echo "head_tree $head_tree"
  echo "docs_tree $docs_tree"
  echo "tag_obj $tag_obj"
  echo "hello_blob $hello_blob"
  echo "note_blob $note_blob"
  echo "# git hash-object cross-checks"
  echo "hello_payload $(printf 'hello\n' | git hash-object --stdin)"
} > "$here/manifest.txt"

echo "=== verify-pack (ofs) ==="
git -C "$ofsrepo" verify-pack -v .git/objects/pack/*.idx | grep -E 'delta|chain' | head -20 || true
echo "=== fixtures written to $here ==="
ls -R "$here"
cat "$here/manifest.txt"
